In [ ]:
#Problem 1
#1
import numpy as np
emptyArr = np.empty((2,2))
print(emptyArr)


[[1.75602544e-315 0.00000000e+000]
 [6.84311763e-310 5.77904633e-317]]


In [ ]:
#2
import numpy as np
Arr = np.ones((4,2))
print(Arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3
import numpy as np
fullArr = np.full((2,2),1)
print(fullArr)

[[1 1]
 [1 1]]


In [ ]:
#4
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
zerosLiker = np.zeros_like(a)
print(zerosLiker)

[[0 0 0]
 [0 0 0]]


In [ ]:
#5
import numpy as np
a=np.array([[2,2],[3,3]])
oneLiker = np.ones_like(a)
print(oneLiker)

[[1 1]
 [1 1]]


In [ ]:
#6
import numpy as np
new_list = [1,2,3,4]
arrayTime = np.array(new_list)
print(arrayTime)

[1 2 3 4]


In [ ]:
#Problem 2
#1
import numpy as np
arr=np.arange(10,50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2
import numpy as np
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3
import numpy as np
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4
randomStuff = np.random.random(30)
average = randomStuff.mean()
print(randomStuff)
print(f"Mean:{average}")

[0.61153959 0.57091307 0.03506535 0.71909266 0.40116981 0.53981126
 0.06219868 0.81347337 0.77257847 0.37899383 0.63902203 0.54271169
 0.88265522 0.69637129 0.2135242  0.7469545  0.92609945 0.76381958
 0.71524303 0.18988371 0.99182244 0.49249449 0.89818939 0.67790461
 0.25190555 0.47344212 0.98322215 0.529067   0.60101575 0.67745492]
Mean:0.5932546405340527


In [ ]:
#5
randomly = np.random.random((10,10))
mini= randomly.min()
notMini = randomly.max()
print(randomly)
print(f"min: {mini}")
print(f"max: {notMini}")

[[0.53167644 0.17119372 0.471923   0.8351151  0.48893265 0.09122458
  0.20792932 0.04805362 0.60654202 0.68916267]
 [0.62304637 0.8858898  0.40843402 0.6391797  0.69622524 0.64000405
  0.70945361 0.36681045 0.16720335 0.77496798]
 [0.32596038 0.00986161 0.06053953 0.48941274 0.83964289 0.77544204
  0.02539964 0.3728416  0.50194737 0.20541176]
 [0.31342238 0.27588643 0.81020094 0.61645927 0.92052547 0.76053517
  0.13302361 0.28671645 0.85894299 0.05347162]
 [0.03771378 0.48091492 0.29412407 0.84925016 0.41032712 0.33627063
  0.20484181 0.82922519 0.03655072 0.44701148]
 [0.93321388 0.65268925 0.7228025  0.25032842 0.8320241  0.31540111
  0.61558696 0.88000008 0.77262358 0.53976931]
 [0.70998358 0.33607894 0.22083292 0.27414882 0.74593967 0.38778324
  0.40267124 0.5481558  0.35423216 0.2209252 ]
 [0.91725149 0.32770792 0.22871377 0.02390078 0.93755538 0.24733661
  0.83437757 0.25105647 0.38617233 0.9834903 ]
 [0.48011202 0.33689964 0.08068369 0.45800019 0.40801699 0.49619767
  0.74379775

In [ ]:
#6
geass = np.zeros(10)
geass[4] = 1
print(geass)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7
arr = [1,2,0,0,4,0]
reverser = arr[::-1]
print(reverser)


[0, 4, 0, 0, 2, 1]


In [ ]:
#8
arr = np.ones((6,6))
arr[1:-1,1:-1]=0
print(arr)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
#9
checker = np.zeros((8,8))
checker[1::2,::2] = 1
checker[::2,1::2]=1
print(checker)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Problem 3
#1
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

sum = x + y
print(sum)


[[ 6  8]
 [10 13]]


In [ ]:
#2
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
sub= x-y
print(sub)

[[-4 -4]
 [-4 -3]]


In [ ]:
#3
x = np.array([[1, 2], [3, 5]])
mult = x*2
print(mult)


[[ 2  4]
 [ 6 10]]


In [ ]:
#4
x = np.array([[1, 2], [3, 5]])
square = x**2
print(square)

[[ 1  4]
 [ 9 25]]


In [ ]:
#5
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

vwDot = np.dot(v,w)
xvDot = np.dot(x,v)
xyDot = np.dot(x,y)

print(vwDot)
print(xvDot)
print(xyDot)



219
[29 77]
[[19 22]
 [50 58]]


In [ ]:
#6
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10]).reshape(2,1)
w = np.array([11,12]).reshape(2,1)
xy = np.concatenate((x,y),axis =0)
vw = np.concatenate((v,w),axis =1)
print(xy)
print(vw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [ ]:
#7
x = np.array([[1,2],[3,5]])
#v = np.array([9,10])
#because x is a 2D array whreas v is a 1D array
#to fix
v = np.array([9,10]).reshape(1,2)
contra = np.concatenate((x,v),axis =0)
print(v)
print(f"to fix: {contra}")


[[ 9 10]]
to fix: [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
#Problem 4
#1
A = np.array([[3, 4], [7, 8]])

aInv = np.linalg.inv(A)
result = np.dot(A,aInv)
print("A inv is :" , aInv)
print("A * Ainv: ",result )


A inv is : [[-2.    1.  ]
 [ 1.75 -0.75]]
A * Ainv:  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#2
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A,B)
BA = np.dot(B,A)
print(AB)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [ ]:
#3
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A,B)

left = AB.T

aFlip = A.T
bFlip = B.T

right  = np.dot(bFlip,aFlip)
print(left)

print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:

#4
A = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
])

B = np.array([-1, -3, 9])

solution = np.linalg.solve(A, B)

print("Solution", solution)


Solution [ 2.  1. -2.]


In [ ]:
#4.2

import time
import random
import numpy as np

list1 = [random.random() for _ in range(1_000_000)]
list2 = [random.random() for _ in range(1_000_000)]

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()
print("Python list addition time:", end - start, "seconds")
arr1 = np.random.rand(1_000_000)
arr2 = np.random.rand(1_000_000)

start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy addition time:", end - start, "seconds")



Python list addition time: 0.20411324501037598 seconds
NumPy addition time: 0.004433870315551758 seconds


In [ ]:
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")

start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy multiplication time:", end - start, "seconds")


Python list multiplication time: 0.12603068351745605 seconds
NumPy multiplication time: 0.0028846263885498047 seconds
